### ISSUE TITLE
First time kick-start... 

### ISSUE THREAD

**Issue by SRHarrison** [Coastal-Imaging-Research-Network/PIXel-Toolbox#1]
Hi All, 
I'm new to the PIXel-Toolbox and unclear as to how to use it. Judging by the manual, it looks like the toolbox will be pretty useful.

I have been collecting video timestacks using hotm. Hotm extracts video at all of the pixels specified in my pixel list - which includes all of my pixel instruments in a single list. I.e. all of the instruments are contained in a single stack .ras file. 

Given that I'm starting with a .ras file, where do I begin? 
Is there a tool to tease out the instruments from the .ras file? 

Thanks for the nudge,
Shawn

**Comment by SRHarrison** [comment]
Similar question: Does anyone know how to easily read a "dump" from hotm? A dump should be the image cube (i.e. video) of the collection. It looks binary... I can try to sense it's format, but thought there might be an existing tool to access it (besides postprocGigE.c).

**Comment by jstanleyx** [comment]
Shawn pointed out to me that he'd made this post, but I hadn't seen it yet, and I answered in email the same question. Here's some skinny:

The .ras file has the pixel data for the stack collection, but has a considerable amount of other stuff, too. These are Sun "rasterfile" image format, which was selected initially because it allowed the users to use any handy Sun image display program to look at the collected stack and see if it looked usable for anything. (Not fogged in, etc.) That was before the pixel toolbox was written, and now the pixel collection is sorted by U/V so runup lines, e.g., might be spread throughout the image instead of next to each other.

The first 8 lines has encoded into it some basics about the pixel list file name, collection parameters, etc. It also contains an encoded form of the U and V values for each column in the data array. 

Each line of the stack after that has the collection time (in milliseconds since the reference time encoded in the first 8 lines) for each line, the pixel data (in U/V order matching the encoded values) and then the gain and shutter time for the camera. 

To decode all of this, the easiest way is to use loadStack.m. That function adds an in-memory cache specific for the stack file so that loading the same stack again does not invoke the extreme time penalty of uncompressing, loading, and decoding the .ras again. The actual workhorse is loadStackFile.m which handles determining if the .ras is actually .ras.gz or .ras.Z and uncompressing it, or if it is a .nc (netCDF) format file. 

There is still some database dependency in the CIRN version of this function. Shawn may be a good source of hints on how to get around that, until the extremely slow and obnoxious author of this code fixes it. 

Higher level code (loadFullInstFromStack, e.g.) makes use of something called the 'r' struct stored (in CIL hierarchy) in /ftp/pub/stationName/collects/epochtime.mat, which in CIL format matches the pixel lists named epochtime.c?.pix. That pixel list file name is how the correct 'r' struct is located. 

In any case, the 'r' struct contains the assigned names and types of instruments and associated UV and camera information. You can see what 'r' looks like since it is stored as an output of AIIIPixScheduleCollect.

**Comment by jstanleyx** [comment]
Oh, a bit I forgot to mention. Rasterfile format was also selected because it is inherently not lossy compressed, a "feature" of JPEG or other formats that would destroy the encoded information. Stacks at CIL are routinely compressed now with gzip, previously with "compress" which is obsolete. Gzip and compress are both lossless so not as efficient as JPEG, but also not destructive of the data.
